version: 1.0.{build}
clone_depth: 1
environment:
  Appveyor: true
services: mssql2016
nuget:
  account_feed: true
  project_feed: true
build_script:
- cmd: >-
    dotnet restore

    dotnet pack Sql.Migrations --version-suffix=b%APPVEYOR_BUILD_NUMBER%

    appveyor PushArtifact Sql.Migrations/bin/Debug/Sql.Migrations.1.0.0-b%APPVEYOR_BUILD_NUMBER%.nupkg

    appveyor PushArtifact Sql.Migrations/bin/Debug/Sql.Migrations.1.0.0-b%APPVEYOR_BUILD_NUMBER%.symbols.nupkg
test_script:
- cmd: dotnet test Sql.Migrations.Tests
notifications:
- provider: HipChat
  room: Weichenwerk
  auth_token:
    secure: lk9q8AL0m0O8h9WUBhMfcGdVaznvV/YOEbsXF9DgJtGkKALSHDg4ivsm3sCj5azU
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: true
